"""Baseline rules — rolling z-score and percentile-based alerts.

These serve as an interpretable benchmark before applying ML.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime

import numpy as np

logger = logging.getLogger(__name__)


@dataclass
class BaselineAlert:
    """An alert generated by baseline rules."""

    timestamp: datetime
    rule_name: str
    metric_name: str
    current_value: float
    baseline_value: float
    z_score: float
    percentile: float
    severity: str  # "low", "medium", "high"
    message: str


class PersonalBaseline:
    """Tracks rolling statistics to establish personal performance baseline.

    Uses Welford's online algorithm for numerically stable rolling mean/variance.
    """

    def __init__(self, window_size: int = 100) -> None:
        self._window_size = window_size
        self._metrics: dict[str, list[float]] = {}

    def update(self, metric_name: str, value: float) -> None:
        """Add a new observation for a metric."""
        if metric_name not in self._metrics:
            self._metrics[metric_name] = []
        self._metrics[metric_name].append(value)
        # Keep only the last window_size values
        if len(self._metrics[metric_name]) > self._window_size:
            self._metrics[metric_name] = self._metrics[metric_name][-self._window_size :]

    def get_stats(self, metric_name: str) -> tuple[float, float, int]:
        """Return (mean, std, count) for a metric."""
        values = self._metrics.get(metric_name, [])
        if len(values) < 2:
            return 0.0, 1.0, len(values)
        arr = np.array(values)
        return float(np.mean(arr)), float(np.std(arr, ddof=1)), len(values)

    def z_score(self, metric_name: str, value: float) -> float:
        """Compute z-score of a value relative to the personal baseline."""
        mean, std, count = self.get_stats(metric_name)
        if count < 5 or std < 1e-8:
            return 0.0
        return (value - mean) / std

    def percentile(self, metric_name: str, value: float) -> float:
        """Compute percentile rank of a value (0-100)."""
        values = self._metrics.get(metric_name, [])
        if len(values) < 5:
            return 50.0
        arr = np.array(values)
        return float(np.sum(arr <= value) / len(arr) * 100)


class BaselineRuleEngine:
    """Generates alerts based on rolling z-scores and percentile thresholds.

    Rules:
    1. High context switching: switches_15m z-score > 1.5
    2. Short focus blocks: mean_focus_block below 20th percentile
    3. High idle ratio: idle_ratio z-score > 1.5
    4. Long session without break: session_age > baseline 80th percentile
    5. Declining input rate: keyboard_rate z-score < -1.5
    """

    def __init__(self, baseline: PersonalBaseline | None = None) -> None:
        self.baseline = baseline or PersonalBaseline()
        self._alert_history: list[BaselineAlert] = []

    def evaluate(
        self, features: dict[str, float | int], at_time: datetime
    ) -> list[BaselineAlert]:
        """Evaluate all baseline rules against current features.

        Args:
            features: Current feature vector from FeaturePipeline.
            at_time: Current timestamp.

        Returns:
            List of triggered alerts (may be empty).
        """
        alerts: list[BaselineAlert] = []

        # Update baseline with current values
        for key, value in features.items():
            if isinstance(value, (int, float)):
                self.baseline.update(key, float(value))

        # Rule 1: High context switching
        if "switches_15m" in features:
            z = self.baseline.z_score("switches_15m", float(features["switches_15m"]))
            pct = self.baseline.percentile("switches_15m", float(features["switches_15m"]))
            if z > 1.5:
                alerts.append(
                    BaselineAlert(
                        timestamp=at_time,
                        rule_name="high_switching",
                        metric_name="switches_15m",
                        current_value=float(features["switches_15m"]),
                        baseline_value=self.baseline.get_stats("switches_15m")[0],
                        z_score=z,
                        percentile=pct,
                        severity="medium" if z < 2.0 else "high",
                        message=(
                            f"Context switches are {z:.1f} std above your baseline "
                            f"({pct:.0f}th percentile)."
                        ),
                    )
                )

        # Rule 2: Short focus blocks
        if "mean_focus_block_sec" in features:
            pct = self.baseline.percentile(
                "mean_focus_block_sec", float(features["mean_focus_block_sec"])
            )
            if pct < 20 and features["mean_focus_block_sec"] > 0:
                z = self.baseline.z_score(
                    "mean_focus_block_sec", float(features["mean_focus_block_sec"])
                )
                alerts.append(
                    BaselineAlert(
                        timestamp=at_time,
                        rule_name="short_focus",
                        metric_name="mean_focus_block_sec",
                        current_value=float(features["mean_focus_block_sec"]),
                        baseline_value=self.baseline.get_stats("mean_focus_block_sec")[0],
                        z_score=z,
                        percentile=pct,
                        severity="medium",
                        message=(
                            f"Focus blocks are shorter than usual "
                            f"(bottom {pct:.0f}% of your history)."
                        ),
                    )
                )

        # Rule 3: High idle ratio
        if "idle_ratio" in features:
            z = self.baseline.z_score("idle_ratio", float(features["idle_ratio"]))
            if z > 1.5:
                pct = self.baseline.percentile("idle_ratio", float(features["idle_ratio"]))
                alerts.append(
                    BaselineAlert(
                        timestamp=at_time,
                        rule_name="high_idle",
                        metric_name="idle_ratio",
                        current_value=float(features["idle_ratio"]),
                        baseline_value=self.baseline.get_stats("idle_ratio")[0],
                        z_score=z,
                        percentile=pct,
                        severity="low",
                        message=f"Idle time is unusually high ({z:.1f} std above baseline).",
                    )
                )

        # Rule 4: Long session without break
        if "time_since_last_break_min" in features:
            pct = self.baseline.percentile(
                "time_since_last_break_min", float(features["time_since_last_break_min"])
            )
            if pct > 85:
                z = self.baseline.z_score(
                    "time_since_last_break_min",
                    float(features["time_since_last_break_min"]),
                )
                alerts.append(
                    BaselineAlert(
                        timestamp=at_time,
                        rule_name="long_session",
                        metric_name="time_since_last_break_min",
                        current_value=float(features["time_since_last_break_min"]),
                        baseline_value=self.baseline.get_stats("time_since_last_break_min")[0],
                        z_score=z,
                        percentile=pct,
                        severity="medium" if pct < 95 else "high",
                        message=(
                            f"Working for {features['time_since_last_break_min']:.0f} "
                            f"min without a break (top {100 - pct:.0f}% longest)."
                        ),
                    )
                )

        # Rule 5: Declining keyboard rate
        if "kb_rate_change_pct" in features and features["kb_rate_change_pct"] < -30:
            z = self.baseline.z_score(
                "keyboard_rate", float(features.get("keyboard_rate", 0))
            )
            alerts.append(
                BaselineAlert(
                    timestamp=at_time,
                    rule_name="declining_input",
                    metric_name="kb_rate_change_pct",
                    current_value=float(features["kb_rate_change_pct"]),
                    baseline_value=0.0,
                    z_score=z,
                    percentile=50.0,
                    severity="low",
                    message=(
                        f"Typing rate dropped {abs(features['kb_rate_change_pct']):.0f}% "
                        "vs your session average."
                    ),
                )
            )

        self._alert_history.extend(alerts)
        return alerts

    @property
    def alert_count(self) -> int:
        return len(self._alert_history)

    def get_risk_score(self, features: dict[str, float | int]) -> float:
        """Simple rule-based risk score (0.0 - 1.0).

        Based on z-scores of key behavioral metrics.
        """
        risk_factors: list[float] = []

        for metric in ["switches_15m", "idle_ratio", "time_since_last_break_min"]:
            if metric in features:
                z = abs(self.baseline.z_score(metric, float(features[metric])))
                risk_factors.append(min(z / 3.0, 1.0))  # Normalize to 0-1

        if "mean_focus_block_sec" in features and features["mean_focus_block_sec"] > 0:
            pct = self.baseline.percentile(
                "mean_focus_block_sec", float(features["mean_focus_block_sec"])
            )
            risk_factors.append(max(0, (50 - pct) / 50))  # Lower pct = higher risk

        if not risk_factors:
            return 0.0

        return float(np.mean(risk_factors))
